version: '2'
services:
  db:
    image: rethinkdb:latest
    ports:
      - "38080:8080"
  web:
    image: markwatsonatx/node-alpine:latest
    volumes:
      - ./public/
    working_dir: /usr/src/app
    ports:
      - "33000:3000"
    depends_on:
      - db
